In [4]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [6]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
a[:,2] = 20

In [8]:
print(a)

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]
